=== sebampuero/restful-ws-ipg/Data/firmendaten.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>

    <xs:element name='firmenliste'>
        <xs:complexType>
            <xs:sequence>
            
                <xs:element name='firma' maxOccurs='unbounded'>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name='branche' type='xs:string'/>
                            <xs:element name='strasse_hnr' type='xs:string'/>
                            <xs:element name='adresszusatz' type='xs:string' minOccurs='0'/>
                            <xs:element name='plz' type='xs:string'/>
                            <xs:element name='ort' type='xs:string'/>
                            <xs:element name='land' type='landListe'/>
                            <xs:element name='website' type='xs:anyURI'/>
                            <xs:element name='ansprechpartner' maxOccurs='3' type='apPerson'/>
                            <xs:element name='erfassungsdatum' type='xs:date'/>
                        </xs:sequence>
                        <xs:attribute name='name' use='required'/>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
            <xs:attribute name='version' use='required' type='xs:integer'/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="apPerson">
        <xs:sequence>
            <xs:element name='anrede' type='xs:string'/>
            <xs:element name='titel' type='xs:string' minOccurs='0'/>
            <xs:element name='funktion' type='xs:string' minOccurs='0'/>
            <xs:element name='telefon' type='xs:string'/>
            <xs:element name='fax' type='xs:string' minOccurs='0'/>
            <xs:element name='email' type='emailAdresse'/>
        </xs:sequence>
        <xs:attribute name='name' use='required'/>
    </xs:complexType>

    <xs:simpleType name="landListe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DE"/>
            <xs:enumeration value="AT"/>
            <xs:enumeration value="CH"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailAdresse"> 
        <xs:restriction base="xsd:string"> 
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction> 
    </xs:simpleType> 

</xs:schema>

=== sebampuero/restful-ws-ipg/Data/firmendaten.xml
<?xml version="1.0" encoding="UTF-8"?>
<firmenliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	         xsi:noNamespaceSchemaLocation="firmendaten.xsd"
             version="1">
    
    <firma name="4system GmbH">
        <branche>E-Learning</branche>
        <strasse_hnr>Kurfrstenstraße 114</strasse_hnr>
        <plz>10787</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.4system.com</website>
        <ansprechpartner name="Dawid Kosc">
            <anrede>Herr</anrede>
            <telefon>030 23 63 16 73</telefon>
            <fax>23 63 16 74</fax>
            <email>d.kosc@4system.com</email>
        </ansprechpartner>
        <erfassungsdatum>2009-06-18</erfassungsdatum>
    </firma>

    <firma name="Aastra Deutschland GmbH">
        <branche>N/A</branche>
        <strasse_hnr>Zeughofstr. 1</strasse_hnr>
        <plz>10997</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.aastra.de</website>
        <ansprechpartner name="Jürgen Signer">
            <anrede>Herr</anrede>
            <funktion>GF</funktion>
            <telefon>030 6104 2007</telefon>
            <fax>6104 2008</fax>
            <email>info.de@aastra.com</email>
        </ansprechpartner>
        <ansprechpartner name="Anthony Shen">
            <anrede>Herr</anrede>
            <telefon>030 6104 2007</telefon>
            <fax>6104 2008</fax>
            <email>info.de@aastra.com</email>
        </ansprechpartner>
        <erfassungsdatum>2012-01-31</erfassungsdatum>
    </firma>

    <firma name="42com Telecommunication GmbH">
        <branche>Telekommunikation</branche>
        <strasse_hnr>Straße der Pariser Kommune 12-16</strasse_hnr>
        <plz>10243</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.42com.com</website>
        <ansprechpartner name="Mochael Palmer">
            <anrede>Herr</anrede>
            <telefon>030 243 42 99 33</telefon>
            <email>michael.palmer@42com.com</email>
        </ansprechpartner>
        <erfassungsdatum>2012-01-31</erfassungsdatum>
    </firma>

    <firma name="A.M.M. Aktionszentrum Multi Media GmbH">
        <branche>Multimedia</branche>
        <strasse_hnr>August-Bebel-Str. 68</strasse_hnr>
        <plz>14482</plz>
        <ort>Potsdam</ort>
        <land>DE</land>
        <website>http://www.amm-gruppe.de</website>
        <ansprechpartner name="Kathrin Schwarz">
            <anrede>Frau</anrede>
            <funktion>GF</funktion>
            <telefon>0331 740 60 84</telefon>
            <fax>740 60 85</fax>
            <email>info@amm-gruppe.de</email>
        </ansprechpartner>
        <ansprechpartner name="Stefan Schwarz">
            <anrede>Herr</anrede>
            <telefon>0331 740 60 84</telefon>
            <fax>740 60 85</fax>
            <email>info@amm-gruppe.de</email>
        </ansprechpartner>
        <erfassungsdatum>2010-10-05</erfassungsdatum>
    </firma>

    <firma name="adKor GmbH">
        <branche>Kommunikationstechnik</branche>
        <strasse_hnr>Am Kleingewerbegebiet 8</strasse_hnr>
        <plz>15745</plz>
        <ort>Wildau</ort>
        <land>DE</land>
        <website>http://www.adkor.de</website>
        <ansprechpartner name="Hartmut Kordus">
            <anrede>Herr</anrede>
            <titel>Dipl.-Ing.</titel>
            <telefon>03375 21 40 53</telefon>
            <fax>21 40 56</fax>
            <email>hartmut.kordus@adkor.de</email>
        </ansprechpartner>
        <erfassungsdatum>2012-01-31</erfassungsdatum>
    </firma>

    <firma name="Airbus Operations GmbH">
        <branche>Luftfahrt</branche>
        <strasse_hnr>Lüneburger Schanze 30</strasse_hnr>
        <plz>21614</plz>
        <ort>Buxtehude</ort>
        <land>DE</land>
        <website>http://www.airbus.com</website>
        <ansprechpartner name="Matthias Schmitt">
            <anrede>Herr</anrede>
            <titel>Dipl.-Ing.</titel>
            <telefon>040 743 784 56</telefon>
            <email>matthias.schmitt@airbus.de</email>
        </ansprechpartner>
        <erfassungsdatum>2011-07-15</erfassungsdatum>
    </firma>

    <firma name="Akademie der Bundeswehr für Information und Kommunikation">
        <branche>Verteidigung</branche>
        <strasse_hnr>Prötzeler Chaussee 20</strasse_hnr>
        <plz>15344</plz>
        <ort>Strausberg</ort>
        <land>DE</land>
        <website>http://www.bundeswehr.org</website>
        <ansprechpartner name="Bernd Stichling">
            <anrede>Herr</anrede>
            <telefon>03341 58 16 91</telefon>
            <fax>58 16 45</fax>
            <email>berndstichling@bundeswehr.org</email>
        </ansprechpartner>
        <erfassungsdatum>2008-01-04</erfassungsdatum>
    </firma>

    <firma name="alphaQuest GmbH">
        <branche>Mobile Anwendungen</branche>
        <strasse_hnr>Theodor-Ott-Ring 34</strasse_hnr>
        <plz>89182</plz>
        <ort>Bernstadt</ort>
        <land>DE</land>
        <website>http://www.alphaQuest.de</website>
        <ansprechpartner name="André Probst">
            <anrede>Herr</anrede>
            <telefon>07348 9670446</telefon>
            <fax>9670447</fax>
            <email>info@alphaQuest.de</email>
        </ansprechpartner>
        <erfassungsdatum>2012-05-29</erfassungsdatum>
    </firma>

    <firma name="Andracor GmbH">
        <branche>N/A</branche>
        <strasse_hnr>Mertensstraße 127 - 131</strasse_hnr>
        <plz>13587</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.andracor.com</website>
        <ansprechpartner name="Benjamin Leschnitzer">
            <anrede>Herr</anrede>
            <telefon>030 850 14 262</telefon>
            <email>leschnitzer@andracor.com</email>
        </ansprechpartner>
        <erfassungsdatum>2011-07-07</erfassungsdatum>
    </firma>

    <firma name="araneaNET GmbH">
        <branche>Netzwerkmanagement</branche>
        <strasse_hnr>Steinstraße 1</strasse_hnr>
        <plz>14482</plz>
        <ort>Potsdam</ort>
        <land>DE</land>
        <website>http://www.araneanet.de</website>
        <ansprechpartner name="Gerald Bock">
            <anrede>Herr</anrede>
            <telefon>0331 55035-0</telefon>
            <email>gerald.bock@araneanet.de</email>
        </ansprechpartner>
        <erfassungsdatum>2008-09-12</erfassungsdatum>
    </firma>

    <firma name="ARC-GREENLAB GmbH">
        <branche>Geoinformatik</branche>
        <strasse_hnr>Eichenstraße 3b</strasse_hnr>
        <plz>12435</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.arc-greenlab.de</website>
        <ansprechpartner name="Wieland Busse">
            <anrede>Herr</anrede>
            <telefon>030 762933331</telefon>
            <email>busse.wieland@arc-greenlab.de</email>
        </ansprechpartner>
        <erfassungsdatum>2010-10-05</erfassungsdatum>
    </firma>

    <firma name="art-X Webargentur Berlin">
        <branche>Webdesign</branche>
        <strasse_hnr>Choriner Str. 78</strasse_hnr>
        <plz>10119</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.art-x.de</website>
        <ansprechpartner name="Folker Silge">
            <anrede>Herr</anrede>
            <titel>Dipl.-Betriebswirt</titel>
            <funktion>Inhaber</funktion>
            <telefon>030 440 47 874</telefon>
            <fax>440 47 873</fax>
            <email>mails@art-x.de</email>
        </ansprechpartner>
        <erfassungsdatum>2010-10-12</erfassungsdatum>
    </firma>

    <firma name="arxes Information Design Berlin GmbH">
        <branche>WLAN</branche>
        <strasse_hnr>Marxstraße 3a</strasse_hnr>
        <plz>13347</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.arxes-berlin.de</website>
        <ansprechpartner name="Uwe Jaroschewski">
            <anrede>Herr</anrede>
            <funktion>GF</funktion>
            <telefon>030 4606 33 33</telefon>
            <fax>4606 31 99</fax>
            <email>uwe.jaroschewski@arxes-berlin.de</email>
        </ansprechpartner>
        <erfassungsdatum>2007-02-08</erfassungsdatum>
    </firma>

    <firma name="ASCI Systemhaus GmbH">
        <branche>IT-Dienstleistung</branche>
        <strasse_hnr>Seddiner Straße 5</strasse_hnr>
        <plz>10315</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.asci-systemhaus.de</website>
        <ansprechpartner name="Lutz Langerwisch">
            <anrede>Herr</anrede>
            <titel>Dipl.-Ing.</titel>
            <telefon>030 2934850</telefon>
            <fax>29348511</fax>
            <email>bewerbung@asci-systemhaus.de</email>
        </ansprechpartner>
        <erfassungsdatum>2012-02-02</erfassungsdatum>
    </firma>

    <firma name="asitos GmbH">
        <branche>N/A</branche>
        <strasse_hnr>Bahnhofstraße Halle 7, Raum 8 EG</strasse_hnr>
        <plz>15745</plz>
        <ort>Wildau</ort>
        <land>DE</land>
        <website>http://www.asitos.de</website>
        <ansprechpartner name="Hans-Dieter Doll">
            <anrede>Herr</anrede>
            <funktion>GF</funktion>
            <telefon>03375 52 17 86</telefon>
            <email>info@asitos.de</email>
        </ansprechpartner>
        <ansprechpartner name="Tanja S. Strauss">
            <anrede>Frau</anrede>
            <telefon>03375 52 17 86</telefon>
            <email>info@asitos.de</email>
        </ansprechpartner>
        <erfassungsdatum>2011-07-07</erfassungsdatum>
    </firma>

    <firma name="Axentris Informationssysteme GmbH">
        <branche>N/A</branche>
        <strasse_hnr>Hohenzollerndamm 152</strasse_hnr>
        <plz>14199</plz>
        <ort>Berlin</ort>
        <land>DE</land>
        <website>http://www.axentris.de</website>
        <ansprechpartner name="Stefan Koch">
            <anrede>Herr </anrede>
            <titel>Dr.</titel>
            <funktion>GF</funktion>
